export const STORE_POST = "STORE_POST"
export const FETCH_ALL_POST = "FETCH_ALL_POST"
export const DELETE_POST = "DELETE_POST"

export const SIGN_UP_USER = "SIGN_UP_USER"
export const FETCH_USER_EMAIL ="FETCH_USER_EMAIL"
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS"
